services:
  backend:
    image: mytaskapp
    networks:
      - taskapp
    expose:
      - "3000"
    ports:
      - "8080:3000"
    depends_on:
      - database
    entrypoint: node
    command: ["app.js"]
  database:
    image: mongo
    container_name: taskappmongodb
    networks:
      - taskapp
    volumes:
      - taskapp:/data/db
networks:
  taskapp:
volumes:
  taskapp:
